import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
 import HomePage from './Homepage'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
<div>
  <Head>
    <title>
      Weather- Currency App
    </title>
    <meta name="description" content="Generated by create next app"></meta>
  </Head>
  <HomePage/>

</div>
  )
}
